export const API_CONFIG = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL || "http://localhost:3000",
  ENDPOINTS: {
    AUTH: {
      SIGNUP: "/api/auth/register",
      SIGNIN: "/api/auth/adminLogin",
      UserData: "/api/users/profile/",
      UserUpdate: "/api/auth/updateProfile",
      AddProducts: "/api/products/create",
      GetProducts: "/api/products/",
      AddUsers: "/api/auth/register",
      UpdateProduct: "/api/products/",
      DeleteProduct: "/api/products/",
      SuspendUser: "/api/users/suspend/",
      ActivateUser: "/api/users/activate/",
      GetUsers: "/api/users",
      UpdateUser: "/api/users/",
      DeleteUser: "/api/users/",
      GetTickets: "/api/tickets",
      UpdateTicket: "/api/tickets/",
      ReplyTicket: "/api/tickets/reply/",
      SetPassword: "/api/auth/setPassword/",
      getSales: "/api/payment/",
      getEmail: "/api/reports/",
      getWithdrawal: "/api/withdrawal/history/",
      getAccountBalance: "/api/account/bank-wallet/",
      updateWithdrawal: "/api/withdrawal/admin/status/",
      getPendingWithdrawals: "/api/withdrawal/admin/pending",
      getPromotions: "/api/promotion/status/",
      updatePromotion: "/api/promotion/status/",
      SubmitSale: "/api/promotion/",
      getCharts: "/api/sales-chart/admin",
    },
  },
};

export const apiUrl = (endpoint: string) => `${API_CONFIG.BASE_URL}${endpoint}`;
